### ISSUE TITLE
1.9.0b6 does not build with SELinux disabled

### ISSUE THREAD

**Issue by pbrezina** [pbrezina/sssd-test#1484]
Cloned from Pagure issue: https://pagure.io/SSSD/sssd/issue/1480
- Created at 2012-08-15 14:47:08 by [grawity](https://pagure.io/user/grawity)
- Closed as Fixed
- Assigned to [jhrozek](https://pagure.io/user/jhrozek)
---

Building sssd 1.9.0beta6 or current Git master on a system where SELinux is not present fails with the following error message:

    src/responder/pam/pamsrv_cmd.c:36:29: fatal error: selinux/selinux.h: No such file or directory

This appears to have been introduced in commit 300c77276.

### Comments

---

**Comment from [grawity](https://pagure.io/user/grawity) at [2012-08-15 14:58:37](https://pagure.io/SSSD/sssd/issue/1480#242992)**

Is it the dependency on the selinux-devel or SELinux in general? I do not see a reason why we should not require an selinux-devel package by default and not build with it only if it is explicitly disabled at build time using some kind of --no-selinux-integration flag or similar.

---

**Comment from [grawity](https://pagure.io/user/grawity) at [2012-08-15 15:07:09](https://pagure.io/SSSD/sssd/issue/1480#242993)**

Dmitri, we DO have a --without-selinux configure flag. What he is reporting is that our recent addition of SELinux user contexts with FreeIPA is not properly honoring that flag. We're trying to build it unconditionally. This is incorrect (we need to support building on platforms that do not have SELinux).

This is a regression and needs to be fixed before 1.9.0 is released.

component: SSSD => Build Environment
keywords:  => Regression
priority: minor => blocker
rhbz:  => 0

---

**Comment from [grawity](https://pagure.io/user/grawity) at [2012-08-15 15:13:48](https://pagure.io/SSSD/sssd/issue/1480#242994)**

Thank you for the bug report. I've just posted a patch to the upstream devel list. I'll let you know once it's pushed to master so that you can cherry-pick it and include for build for your distribution (I assume you are building beta6 for a non-Fedora/non-Red Hat distro)

owner: somebody => jhrozek
patch: 0 => 1
status: new => assigned

---

**Comment from [grawity](https://pagure.io/user/grawity) at [2012-08-16 11:12:01](https://pagure.io/SSSD/sssd/issue/1480#242995)**

Fixed in af824bac568ebe8a03273f73246ac78b415ea756

milestone: NEEDS_TRIAGE => SSSD 1.9.0 RC1
resolution:  => fixed
status: assigned => closed

---

**Comment from [grawity](https://pagure.io/user/grawity) at [2012-08-16 11:15:53](https://pagure.io/SSSD/sssd/issue/1480#242996)**

Replying to [comment:3 jhrozek]:
> Thank you for the bug report. I've just posted a patch to the upstream devel list. I'll let you know once it's pushed to master so that you can cherry-pick it and include for build for your distribution (I assume you are building beta6 for a non-Fedora/non-Red Hat distro)

You obtain the patch from our upstream repository with:

    git format-patch -1 af824bac568ebe8a03273f73246ac78b415ea756

Or just download the single patch file here:

    http://git.fedorahosted.org/cgit/sssd.git/patch/?id=af824bac568ebe8a03273f73246ac78b415ea756

Thank you again for the bug report.

---

**Comment from [grawity](https://pagure.io/user/grawity) at [2017-02-24 15:07:51](https://pagure.io/SSSD/sssd/issue/1480#242997)**

**Metadata Update from @grawity**:
- Issue assigned to jhrozek
- Issue set to the milestone: SSSD 1.9.0 beta 7
