### ISSUE TITLE
SSSD needs configure test for sasl.h

### ISSUE THREAD

**Issue by pbrezina** [pbrezina/sssd-test#257]
Cloned from Pagure issue: https://pagure.io/SSSD/sssd/issue/253
- Created at 2009-11-03 20:44:23 by [sgallagh](https://pagure.io/user/sgallagh)
- Closed as Fixed
- Assigned to [sgallagh](https://pagure.io/user/sgallagh)
---

Attempting to build on Ubuntu 9.10:

    ../../server/providers/ldap/sdap_async.c:22:23: error: sasl/sasl.h: No such file or directory
    ../../server/providers/ldap/sdap_async.c: In function ‘sdap_sasl_interact’:
    ../../server/providers/ldap/sdap_async.c:905: error: ‘sasl_interact_t’ undeclared (first use in this function)
    ../../server/providers/ldap/sdap_async.c:905: error: (Each undeclared identifier is reported only once
    ../../server/providers/ldap/sdap_async.c:905: error: for each function it appears in.)
    ../../server/providers/ldap/sdap_async.c:905: error: ‘in’ undeclared (first use in this function)
    ../../server/providers/ldap/sdap_async.c:905: error: expected expression before ‘)’ token
    ../../server/providers/ldap/sdap_async.c:909: error: ‘SASL_CB_LIST_END’ undeclared (first use in this function)
    ../../server/providers/ldap/sdap_async.c:912: error: ‘SASL_CB_GETREALM’ undeclared (first use in this function)
    ../../server/providers/ldap/sdap_async.c:913: error: ‘SASL_CB_AUTHNAME’ undeclared (first use in this function)
    ../../server/providers/ldap/sdap_async.c:914: error: ‘SASL_CB_PASS’ undeclared (first use in this function)
    ../../server/providers/ldap/sdap_async.c:922: error: ‘SASL_CB_USER’ undeclared (first use in this function)
    ../../server/providers/ldap/sdap_async.c:932: error: ‘SASL_CB_NOECHOPROMPT’ undeclared (first use in this function)
    ../../server/providers/ldap/sdap_async.c:933: error: ‘SASL_CB_ECHOPROMPT’ undeclared (first use in this function)
    make[3]: *** [providers/ldap/libsss_ldap_la-sdap_async.lo] Error 1
    make[3]: Leaving directory `/home/sgallagh/sssd/x64/server'
    make[2]: *** [all-recursive] Error 1
    make[2]: Leaving directory `/home/sgallagh/sssd/x64/server'
    make[1]: *** [all] Error 2
    make[1]: Leaving directory `/home/sgallagh/sssd/x64/server'
    make: *** [all-recursive] Error 1

We should detect the presence of sasl/sasl.h in the configure script and fail if it is not available.

### Comments

---

**Comment from [sgallagh](https://pagure.io/user/sgallagh) at [2009-11-04 19:16:20](https://pagure.io/SSSD/sssd/issue/253#243085)**

Fields changed

status: new => assigned

---

**Comment from [sgallagh](https://pagure.io/user/sgallagh) at [2009-11-05 20:59:32](https://pagure.io/SSSD/sssd/issue/253#243086)**

Fixed in 198e04f81f26c051037817241918178c01803f52

fixedin:  => 1.0.0rc
resolution:  => fixed
status: assigned => closed

---

**Comment from [sgallagh](https://pagure.io/user/sgallagh) at [2012-01-19 02:33:03](https://pagure.io/SSSD/sssd/issue/253#243087)**

Fields changed

rhbz:  => 0

---

**Comment from [sgallagh](https://pagure.io/user/sgallagh) at [2017-02-24 15:08:03](https://pagure.io/SSSD/sssd/issue/253#243088)**

**Metadata Update from @sgallagh**:
- Issue assigned to sgallagh
- Issue set to the milestone: SSSD 1.0 RC
